// Command docgen keeps the runtime-go docs honest. It walks every module in the
// workspace, verifies each Go package carries a doc.go, and regenerates the
// "Packages" table in README.md from the package doc comments — so the README
// always lists every package and a one-line summary pulled straight from its doc.
//
// Run it from anywhere in the repo:
//
//	go run .            # (from tools/docgen) rewrite README.md
//	go run . -check     # validate only: fail if a doc.go is missing or README is stale
//
// The -check mode is what CI runs on every push: it never writes, it just exits
// non-zero (with a clear message) when a package lacks a doc.go or when README.md
// no longer matches the generated table.
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/doc"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	beginMarker = "<!-- BEGIN PACKAGES (generated by tools/docgen; run `make docs` to refresh) -->"
	endMarker   = "<!-- END PACKAGES -->"
)

// pkg is one documented package.
type pkg struct {
	rel        string // path relative to repo root, e.g. "grpc/options"
	importPath string // full import path
	synopsis   string // first sentence of the package doc
	hasDoc     bool   // a doc.go file is present
}

func main() {
	check := flag.Bool("check", false, "validate doc.go presence and README freshness; exit non-zero on failure")
	flag.Parse()

	root, err := findRoot()
	if err != nil {
		fatal(err)
	}
	pkgs, err := collect(root)
	if err != nil {
		fatal(err)
	}

	var missing []string
	for _, p := range pkgs {
		if !p.hasDoc {
			missing = append(missing, p.rel)
		}
	}

	readmePath := filepath.Join(root, "README.md")
	current, err := os.ReadFile(readmePath)
	if err != nil {
		fatal(err)
	}
	updated, err := splice(string(current), section(pkgs))
	if err != nil {
		fatal(err)
	}

	if *check {
		ok := true
		if len(missing) > 0 {
			ok = false
			fmt.Fprintf(os.Stderr, "docgen: %d package(s) missing doc.go:\n", len(missing))
			for _, m := range missing {
				fmt.Fprintf(os.Stderr, "  - %s/doc.go\n", m)
			}
		}
		if updated != string(current) {
			ok = false
			fmt.Fprintln(os.Stderr, "docgen: README.md is out of date — run `make docs` and commit the result.")
		}
		if !ok {
			os.Exit(1)
		}
		fmt.Printf("docgen: OK — %d packages documented, README.md up to date.\n", len(pkgs))
		return
	}

	for _, m := range missing {
		fmt.Fprintf(os.Stderr, "docgen: warning: %s/doc.go is missing\n", m)
	}
	if updated == string(current) {
		fmt.Printf("docgen: README.md already up to date (%d packages).\n", len(pkgs))
		return
	}
	if err := os.WriteFile(readmePath, []byte(updated), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("docgen: wrote README.md (%d packages).\n", len(pkgs))
}

// findRoot walks up from the working directory to the repo root (the directory
// holding go.work).
func findRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.work not found in any parent of %s", dir)
		}
		dir = parent
	}
}

// collect finds every module (a directory with a go.mod) under root and returns
// the documented packages in each, sorted by import path. The docgen tool's own
// module is skipped.
func collect(root string) ([]pkg, error) {
	type module struct{ dir, path string }
	var mods []module
	err := filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if skipDir(root, p, d.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() == "go.mod" {
			mp, err := modulePath(p)
			if err != nil {
				return err
			}
			mods = append(mods, module{filepath.Dir(p), mp})
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	var out []pkg
	for _, m := range mods {
		if strings.HasSuffix(m.path, "/tools/docgen") {
			continue // don't document the generator itself
		}
		err := filepath.WalkDir(m.dir, func(p string, d os.DirEntry, err error) error {
			if err != nil || !d.IsDir() {
				return err
			}
			if p != m.dir && skipDir(root, p, d.Name()) {
				return filepath.SkipDir
			}
			// A nested go.mod is its own module — leave it to that module's walk.
			if p != m.dir {
				if _, err := os.Stat(filepath.Join(p, "go.mod")); err == nil {
					return filepath.SkipDir
				}
			}
			info, ok, err := describe(root, p, m.dir, m.path)
			if err != nil {
				return err
			}
			if ok {
				out = append(out, info)
			}
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].importPath < out[j].importPath })
	return out, nil
}

// skipDir reports whether a directory should be pruned from the walk.
func skipDir(root, p, name string) bool {
	if p == root {
		return false
	}
	return name == "vendor" || name == "testdata" || strings.HasPrefix(name, ".")
}

// describe parses the package rooted at dir and returns its doc info. ok is false
// when the directory holds no buildable (non-test) Go package.
func describe(root, dir, modDir, modPath string) (pkg, bool, error) {
	fset := token.NewFileSet()
	parsed, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return pkg{}, false, fmt.Errorf("parse %s: %w", dir, err)
	}
	var astPkg *ast.Package
	for name, ap := range parsed {
		if strings.HasSuffix(name, "_test") {
			continue
		}
		astPkg = ap
		break
	}
	if astPkg == nil {
		return pkg{}, false, nil
	}

	rel, err := filepath.Rel(modDir, dir)
	if err != nil {
		return pkg{}, false, err
	}
	importPath := modPath
	if rel != "." {
		importPath = modPath + "/" + filepath.ToSlash(rel)
	}
	relRoot, err := filepath.Rel(root, dir)
	if err != nil {
		return pkg{}, false, err
	}

	dp := doc.New(astPkg, importPath, doc.AllDecls)
	_, hasDoc := os.Stat(filepath.Join(dir, "doc.go"))
	return pkg{
		rel:        filepath.ToSlash(relRoot),
		importPath: importPath,
		synopsis:   dp.Synopsis(dp.Doc),
		hasDoc:     hasDoc == nil,
	}, true, nil
}

// modulePath reads the module path from a go.mod file.
func modulePath(goMod string) (string, error) {
	b, err := os.ReadFile(goMod)
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if rest, ok := strings.CutPrefix(line, "module "); ok {
			return strings.TrimSpace(rest), nil
		}
	}
	return "", fmt.Errorf("%s: no module directive", goMod)
}

// section renders the generated Packages block (between the markers).
func section(pkgs []pkg) string {
	var b strings.Builder
	b.WriteString(beginMarker + "\n")
	b.WriteString("## Packages\n\n")
	b.WriteString("`runtime-go` is a Go multi-module workspace — import only the modules you need\n")
	b.WriteString("(the `orm` driver never pulls in go-ethereum, and vice-versa). Every package\n")
	b.WriteString("carries a `doc.go`; this table is generated from those docs by `tools/docgen`\n")
	b.WriteString("(`make docs`). See each package's Go doc for how it works and example usage.\n\n")
	b.WriteString("| Package | Import path | Summary |\n")
	b.WriteString("| --- | --- | --- |\n")
	for _, p := range pkgs {
		b.WriteString(fmt.Sprintf("| [`%s`](%s) | `%s` | %s |\n", p.rel, p.rel, p.importPath, p.synopsis))
	}
	b.WriteString(endMarker)
	return b.String()
}

// splice replaces the marked Packages block in the README, or inserts it before
// "## Contributing" (or appends) on first run.
func splice(current, section string) (string, error) {
	bi := strings.Index(current, beginMarker)
	ei := strings.Index(current, endMarker)
	if bi >= 0 && ei > bi {
		return current[:bi] + section + current[ei+len(endMarker):], nil
	}
	if at := strings.Index(current, "## Contributing"); at >= 0 {
		return current[:at] + section + "\n\n" + current[at:], nil
	}
	return strings.TrimRight(current, "\n") + "\n\n" + section + "\n", nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "docgen:", err)
	os.Exit(1)
}
