package database

import (
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/dynamicpb"

	"github.com/the-protobuf-project/runtime-go/database/store"
)

// Describe derives a [store.Resource] from a Go struct.
//
// It is what lets a caller store an ordinary struct without writing a proto
// descriptor by hand. The layer underneath is unchanged — every driver still
// reads and writes through a Resource — so a type described here and one
// generated by protorm are the same thing to the backend, and can share a
// database.
//
// Fields are read from the `db` tag:
//
//	type Book struct {
//	    ID    string    `db:"id,pk"`
//	    Title string    `db:"title,unique"`
//	    Year  int32     `db:"published_year"`
//	    Added time.Time `db:"added_at,autocreate"`
//	    cache []byte    // unexported: ignored
//	    Tmp   string    `db:"-"`  // explicitly ignored
//	}
//
// The options are:
//
//	pk          the key a record is addressed by, and a primary-key constraint
//	key         the key it is addressed by, with no constraint declared
//	unique      no two records may share this value
//	notnull     the column is required
//	autocreate  the driver stamps it on create
//	autoupdate  the driver stamps it on create and update
//	ulid, uuid  the driver generates it when it is empty
//
// pk and key differ only in what reaches the backend, and the difference
// matters on exactly one kind of table: TimescaleDB requires every unique index
// to contain the partitioning column, so a measurement keyed by id and
// partitioned by time uses key rather than pk.
//
// An untagged exported field takes its own name in snake_case, so a struct with
// no tags at all still works. Exactly one field must be marked pk, because every
// operation in the contract addresses a record by one key.
//
// The result is cached per type: deriving it walks the struct and builds a proto
// descriptor, and doing that on every call would put reflection on the write
// path for no reason.
func Describe[T any](table string) (*store.Resource, error) {
	var zero T
	rt := reflect.TypeOf(zero)
	if rt == nil || rt.Kind() != reflect.Struct {
		return nil, fmt.Errorf("database: Describe needs a struct, got %T", zero)
	}

	key := describeKey{typ: rt, table: table}
	if cached, ok := described.Load(key); ok {
		return cached.(*store.Resource), nil
	}

	res, err := describe(rt, table)
	if err != nil {
		return nil, err
	}
	described.Store(key, res)
	return res, nil
}

type describeKey struct {
	typ   reflect.Type
	table string
}

var described sync.Map // describeKey -> *store.Resource

// field is one struct field paired with the column it became.
type field struct {
	index  int
	column store.Column
}

// describe walks a struct type and builds its Resource.
func describe(rt reflect.Type, table string) (*store.Resource, error) {
	if table == "" {
		table = snake(rt.Name()) + "s"
	}

	var (
		fields  []field
		columns []store.Column
		pk      string
	)
	for i := range rt.NumField() {
		sf := rt.Field(i)
		if sf.PkgPath != "" {
			continue // unexported: not ours to store
		}
		tag := sf.Tag.Get("db")
		if tag == "-" {
			continue
		}

		name, opts := parseTag(tag, sf.Name)
		kind, err := kindOf(sf.Type)
		if err != nil {
			return nil, fmt.Errorf("database: %s.%s: %w", rt.Name(), sf.Name, err)
		}

		// pk and key both name the field a record is addressed by. They differ
		// in what reaches the backend: pk also declares a primary-key
		// constraint, key declares nothing.
		//
		// That distinction exists because TimescaleDB requires every unique
		// index to contain the partitioning column. A measurement keyed by id
		// and partitioned by time cannot have both, so `key` is how a struct
		// says "this is the lookup key" without asking for a constraint the
		// backend will refuse.
		isKey := opts["pk"] || opts["key"]
		col := store.Column{
			Name:       name,
			Field:      protoreflect.Name(name),
			Kind:       kind,
			PrimaryKey: opts["pk"],
			Unique:     opts["unique"],
			NotNull:    opts["notnull"] || isKey,
			AutoCreate: opts["autocreate"],
			AutoUpdate: opts["autoupdate"],
		}
		if opts["ulid"] {
			col.Generated = "ulid"
		}
		if opts["uuid"] {
			col.Generated = "uuid"
		}
		if isKey {
			if pk != "" {
				return nil, fmt.Errorf(
					"database: %s marks both %q and %q as the key; a record is addressed by one",
					rt.Name(), pk, name)
			}
			pk = name
		}

		fields = append(fields, field{index: i, column: col})
		columns = append(columns, col)
	}

	if pk == "" {
		return nil, fmt.Errorf(
			"database: %s has no field tagged `db:\",pk\"` or `db:\",key\"`; every record is addressed by one key",
			rt.Name())
	}

	md, err := buildDescriptor(rt, columns)
	if err != nil {
		return nil, err
	}

	res := &store.Resource{
		Name:     rt.Name(),
		Table:    table,
		PKColumn: pk,
		Columns:  columns,
		New:      func() proto.Message { return dynamicpb.NewMessage(md) },
	}
	fieldsByResource.Store(res, fields)
	return res, nil
}

// fieldsByResource remembers which struct field each column came from, so the
// conversion either way does not re-derive it.
var fieldsByResource sync.Map // *store.Resource -> []field

// parseTag splits `name,opt,opt` and falls back to the field's own name.
func parseTag(tag, fallback string) (string, map[string]bool) {
	opts := map[string]bool{}
	parts := strings.Split(tag, ",")
	name := strings.TrimSpace(parts[0])
	if name == "" {
		name = snake(fallback)
	}
	for _, o := range parts[1:] {
		opts[strings.ToLower(strings.TrimSpace(o))] = true
	}
	return name, opts
}

// kindOf maps a Go type onto the backend-neutral kind.
//
// It deliberately returns no SQL type. A type name is dialect-specific — BLOB is
// not PostgreSQL, TIMESTAMPTZ is not MySQL, BYTEA is neither SQLite nor MySQL —
// so a descriptor derived here naming one would create a table on the engine it
// was guessed for and fail on the rest, which is exactly the portability this
// package claims. The driver knows its dialect; it picks the type.
//
// A descriptor generated by protorm carries its own SQLType, and that is
// honored: it was written for a known target.
func kindOf(t reflect.Type) (store.Kind, error) {
	if t == reflect.TypeOf(time.Time{}) {
		return store.KindTimestamp, nil
	}
	switch t.Kind() {
	case reflect.String:
		return store.KindString, nil
	case reflect.Bool:
		return store.KindBool, nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return store.KindInt, nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return store.KindUint, nil
	case reflect.Float32, reflect.Float64:
		return store.KindFloat, nil
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			return store.KindBytes, nil
		}
		return 0, fmt.Errorf(
			"a %s has no column type; store it as bytes or give it a field of its own", t)
	default:
		return 0, fmt.Errorf(
			"a %s has no column type; the kinds a backend understands are string, integer, float, bool, bytes and time.Time", t)
	}
}

// snake turns a Go identifier into a column name.
//
// A capital starts a new word only where it actually begins one: after a
// lowercase letter or a digit, or at the end of a run of capitals. Without that
// last case an acronym comes apart — UserID becomes user_i_d, and the column a
// caller gets is not the one they wrote.
func snake(s string) string {
	runes := []rune(s)
	var b strings.Builder
	b.Grow(len(runes) + 4)
	for i, r := range runes {
		if r < 'A' || r > 'Z' {
			b.WriteRune(r)
			continue
		}
		if i > 0 {
			prev := runes[i-1]
			prevIsWord := (prev >= 'a' && prev <= 'z') || (prev >= '0' && prev <= '9')
			nextIsLower := i+1 < len(runes) && runes[i+1] >= 'a' && runes[i+1] <= 'z'
			if prevIsWord || nextIsLower {
				b.WriteByte('_')
			}
		}
		b.WriteRune(r + 32)
	}
	return b.String()
}

// buildDescriptor makes the proto message the layer underneath moves values
// through.
//
// It exists because [store.Driver] speaks proto.Message and this package's whole
// point is that a caller does not have to. The message is never seen by the
// caller: it is built here, filled from the struct, and unpacked back into a
// struct on the way out.
func buildDescriptor(rt reflect.Type, columns []store.Column) (protoreflect.MessageDescriptor, error) {
	msg := &descriptorpb.DescriptorProto{Name: proto.String(rt.Name())}
	for i, col := range columns {
		f := &descriptorpb.FieldDescriptorProto{
			Name:   proto.String(col.Name),
			Number: proto.Int32(int32(i + 1)),
			Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
		}
		switch col.Kind {
		case store.KindString:
			f.Type = descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum()
		case store.KindBool:
			f.Type = descriptorpb.FieldDescriptorProto_TYPE_BOOL.Enum()
		case store.KindInt:
			f.Type = descriptorpb.FieldDescriptorProto_TYPE_INT64.Enum()
		case store.KindUint:
			f.Type = descriptorpb.FieldDescriptorProto_TYPE_UINT64.Enum()
		case store.KindFloat:
			f.Type = descriptorpb.FieldDescriptorProto_TYPE_DOUBLE.Enum()
		case store.KindBytes:
			f.Type = descriptorpb.FieldDescriptorProto_TYPE_BYTES.Enum()
		case store.KindTimestamp:
			f.Type = descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum()
			f.TypeName = proto.String(".google.protobuf.Timestamp")
		default:
			return nil, fmt.Errorf("database: column %q has no proto type", col.Name)
		}
		msg.Field = append(msg.Field, f)
	}

	// A file name unique to this type, so two structs described in one process
	// cannot collide in the resolver.
	file := &descriptorpb.FileDescriptorProto{
		Name:        proto.String(fmt.Sprintf("database/derived/%s/%s.proto", sanitize(rt.PkgPath()), rt.Name())),
		Package:     proto.String("database.derived"),
		Syntax:      proto.String("proto3"),
		Dependency:  []string{"google/protobuf/timestamp.proto"},
		MessageType: []*descriptorpb.DescriptorProto{msg},
	}
	fd, err := protodesc.NewFile(file, protoregistry.GlobalFiles)
	if err != nil {
		return nil, fmt.Errorf("database: cannot describe %s: %w", rt.Name(), err)
	}
	return fd.Messages().Get(0), nil
}

// sanitize makes a package path usable inside a proto file name.
func sanitize(path string) string {
	r := strings.NewReplacer("/", "_", ".", "_", "-", "_")
	return r.Replace(path)
}
