// Package database is the backend-agnostic core of the runtime data layer: a single
// CRUD Driver contract that operates on proto messages, a Resource descriptor
// that mirrors protorm's IR at runtime, and a reflection bridge every driver
// reuses to move values between a proto message and a backend column map.
//
// The point is that one runtime drives many backends. A relational driver (the
// database/orm package), an EVM/Solidity driver (blockchain/evm), and a
// Hyperledger driver (blockchain/fabric) all implement the same [Driver]; the
// gRPC adapter (interfaces/adapter) talks only to that interface, so swapping
// the storage backend never touches the proto API. Because Driver works on
// proto.Message via protoreflect, no per-resource Go types are generated — the
// [Resource] descriptor carries everything a driver needs to read and write any
// message dynamically.
//
// This package deliberately depends on nothing but protobuf, so that every
// driver can depend on it. That is why [NewDriver] takes an untyped config: the
// drivers do not share a configuration shape, and a struct covering all of them
// would drag GORM and go-ethereum in here. Prefer a driver's own typed
// constructor when the backend is known at compile time; use [NewDriver] to
// select one by name from configuration.
//
// # Selecting a database, and what a backend cannot do
//
// [Provider] adds the step before CRUD: a client you own, then a database chosen
// from it, then the driver over that database.
//
//	p := orm.NewProvider(gormDB)
//	db, _ := p.SetDatabase(ctx, "tenant_a")
//	defer db.Close()
//
//	db.Schema.EnsureSchema(ctx, res)   // the table the descriptor describes
//	db.Create(ctx, res, book)          // Driver is embedded
//
// A selected name overrides [Resource.Schema] for every resource driven through
// the result, which is what lets one set of generated descriptors serve many
// tenants: the descriptor says what a Book is, the selection says whose.
//
// Backends are not equally capable and the contract says so rather than
// pretending. [Transactional], [Migrator], [Batcher] and [Watcher] are
// implemented by a driver only if it can; [Build] resolves them once and fills
// the gaps with a refusal naming the backend, so [DB.Tx] and [DB.Schema] are
// never nil and a missing capability reports [ErrUnimplemented] instead of
// panicking somewhere far from the wiring that caused it.
//
// # Typed views
//
// [For] binds a driver and a descriptor to one message type, so the descriptor
// stops being an argument on every call and reads stop ending in an assertion
// the compiler cannot check:
//
//	books, _ := database.For[*pb.Book](db, res)
//	b, _ := books.Get(ctx, "books/dune")   // already a *pb.Book
//
// Error contract: drivers return the sentinel errors [ErrNotFound],
// [ErrAlreadyExists], and [ErrUnimplemented] (wrapped is fine — callers use
// errors.Is) so the adapter can map them to gRPC status codes uniformly.
// [ErrBadConfig] reports a driver constructed with the wrong configuration.
//
// # Example
//
// A driver works through a [Resource] descriptor (generated by protorm's
// target=grpc, or built by hand). Register the resources once, then drive any
// backend through the same calls:
//
//	reg := database.NewRegistry(grpcx.Resources...) // []database.Resource from codegen
//	res, _ := reg.Resource("Book")
//
//	book, err := driver.Get(ctx, res, "books/dune") // driver is any database.Driver
//	if errors.Is(err, database.ErrNotFound) {
//	    // ... map to the caller's not-found response
//	}
package database
