services:
  nats-server:
    image: nats:latest
    command: ["-c", "/config/nats-server.conf"]
    volumes:
      - ./nats-data:/data
      - ./nats-server.conf:/config/nats-server.conf
    ports:
      - "4222:4222"
      - "8222:8222"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  nats-ui:
    image: ghcr.io/nats-nui/nui:latest
    depends_on:
      - nats-server
    volumes:
      - ./nui-db:/db
    ports:
      - "31311:31311"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:31311"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
