// Package store is the backend-agnostic core of the runtime data layer: a single
// CRUD Driver contract that operates on proto messages, a Resource descriptor
// that mirrors protorm's IR at runtime, and a reflection bridge every driver
// reuses to move values between a proto message and a backend column map.
//
// The point is that one runtime drives many backends. A relational driver (the
// interfaces/orm package), an EVM/Solidity driver (blockchain/evm), and a
// Hyperledger driver (blockchain/fabric) all implement the same [Driver]; the
// gRPC adapter (interfaces/adapter) talks only to that interface, so swapping
// the storage backend never touches the proto API. Because Driver works on
// proto.Message via protoreflect, no per-resource Go types are generated — the
// [Resource] descriptor carries everything a driver needs to read and write any
// message dynamically.
//
// This package deliberately depends on nothing but protobuf, so that every
// driver can depend on it. That is why [NewDriver] takes an untyped config: the
// drivers do not share a configuration shape, and a struct covering all of them
// would drag GORM and go-ethereum in here. Prefer a driver's own typed
// constructor when the backend is known at compile time; use [NewDriver] to
// select one by name from configuration.
//
// Error contract: drivers return the sentinel errors [ErrNotFound],
// [ErrAlreadyExists], and [ErrUnimplemented] (wrapped is fine — callers use
// errors.Is) so the adapter can map them to gRPC status codes uniformly.
// [ErrBadConfig] reports a driver constructed with the wrong configuration.
//
// # Example
//
// A driver works through a [Resource] descriptor (generated by protorm's
// target=grpc, or built by hand). Register the resources once, then drive any
// backend through the same calls:
//
//	reg := store.NewRegistry(grpcx.Resources...) // []store.Resource from codegen
//	res, _ := reg.Resource("Book")
//
//	book, err := driver.Get(ctx, res, "books/dune") // driver is any store.Driver
//	if errors.Is(err, store.ErrNotFound) {
//	    // ... map to the caller's not-found response
//	}
package store
